### ISSUE TITLE
Tatycraft is not working properly

### ISSUE THREAD

**Issue by Buzznacker** [BenDaviesGFX/BabbleBot-Server#2]
I followed this tutorial and i cannot get the main method to work help pls https://www.youtube.com/watch?v=HTzCbCVX2Co

**Comment by Buzznacker** [comment]
please fix

**Comment by Buzznacker** [comment]
https://ghose.xyz/i/ligzgptc1

**Comment by bendavies99** [comment]
Hi, Sorry this issue is not regarding this project. Please try some tutorials on videos that are made professionally :), I made that video when I was younger.

**Comment by AgentManny** [comment]
You must've have skimmed it, if you watched it fully you would know that he modifies the main class shortly after and that video does seem professional just a bad microphone in my opinion.
